### ISSUE TITLE
popler database appears down

### ISSUE THREAD

**Issue by ha0ye** [weecology/MATSS#101]
We are currently getting an error when trying to download the popler data.

It looks like `popler::pplr_browse()` works, by loading in a local table that is included when installing the `popler` package.

When trying to download using `popler::pplr_get_data()`, we get this error:
```
Error: Bad Request (HTTP 400)
```

Digging into this a bit more, it looks like the functions are formatting an SQL query and sending it to https://popler.space, which is up and running, but might not be linked to the underlying database at the moment.

Sample query link: https://popler.space/search?proj_metadata_key=2&limit=10&offset=0

Next steps are to contact Aldo Compagnoni to see if we can
* get the popler database back online
* mirror it and switch out the base URL for our own purposes
* other? (use BioTIME or some other source for LTER data)

**Comment by ethanwhite** [comment]
Pinging @AldoCompagnoni. Presumably this is the same issue as https://github.com/AldoCompagnoni/popler/issues/57.

**Comment by diazrenata** [comment]
Data has been downloaded, but we need to figure out a permanent storage plan and add code to add it to MATSS (#95)
