### ISSUE TITLE
April 18 notes (MATSS/MATSS-LDATS science questions)

### ISSUE THREAD

**Issue by diazrenata** [weecology/MATSS#114]
## MATSS/MATSS-LDATS ideaspace

Empirical:
  What do we see:
  * how many communities does the LDA find
    * LDA scaling
    * species richness // k
    * spatial scale: downsampling
    * species richness, temporal beta diversity // k
      * core-transient? Ellen
      * species: are there transient species who show up as centers of LDA communities vs transients that don't drive signals in the LDA community because they are ephemeral
  * what kinds of dynamics do we see: nchangepoints, trends
  Where do we see it:
  * decompose into different ecosystems, taxa, etc
  Why do we see it:
  * data on potential drivers

Simulation based (Juniper):
  * What can we get out of a dataset, depending on its characteristics
    * number of samples, number of species, number of time points
    * complexity of timeseries
    * downsampling and simulating
  * Functionality for LDATS

## MATSS prioritization
* Site-level BBS runs for long-term sites through LDATS
  * ...with trends?
* BBS dataset handling (Ethan?)
* Stable data for MATSS (Renata...?)
  * Popler function (Ellen?)
* Skeleton for MATSS-LDATS workflow and report (Renata)
* Computational aspects of LDATS (Juniper)
  * Simulating data to explore boundaries of recoverability (topics & trends)
  * Downsampling: lower limit for timeseries length or sampling for the method to work
* Organize scientific questions for grant
* BioTime and Popler!
* MATSS maintenance and documentation
  * Hipergator deployment: finalize & stabilize
    * Scaling of current implementation (parallelization?)
* Datasets blinking out

**Comment by ha0ye** [comment]
The content of this issue has either been moved to weecology/MATSS-LDATS#18, resolved already, or covered by #115
