### ISSUE TITLE
Add functions to handle and detect non-integer timestep data

### ISSUE THREAD

**Issue by ha0ye** [weecology/MATSS#136]
(subgoal of #96; address weecology/MATSS-LDATS#13)

How about adding the following two functions:
* get_integer_times <- function(data) {...} # returns an integer vector of times
* make_integer_times <- function(data) {...} # returns a modified version of the dataset with integer times

This lets analyses use the integer times if need be, and also process all the datasets, so that they're saved for post-analysis-processing, too.

**Comment by diazrenata** [comment]
latest edit - I am now not sure of anything and think perhaps only MATSS-LDATS needs to change? 😝  I'm going to stop live tweeting via github issues & will let you both know when I know what's up!

I think this should work! @juniperlsimonis, just to double-check, this isn't going to be redundant/at odds with anything you have going in to LDATS 0.2.0? (It doesn't look like it from my first look at the commit log? Next up for me is getting into the LDATS updates in earnest, so apologies if this becomes apparent once I do!) 

Editing - looks like there'll be a little bit of double-coverage with some existing checks but that's not a bad thing. Some things in MATSS and MATSS-LDATS will need to adjust to work with the updates to LDATS, so I've opened a branch to make those adjustments. I think it'll be simplest to wait to add these functions until those adjustments have been made?

In looking into this, it actually looks to me like neither MATSS nor MATSS-LDATS is set up to automatically run checks on data before running it through the pipeline, although the basics of those capabilities are now in MATSS. I think it makes sense for MATSS-LDATS to run those checks, and potentially use the functions you suggest here, early on in the pipeline. So I'll probably be rearranging things anyway to add a data-checking-and-processing step to the MATSS-LDATS pipeline.

**Comment by ha0ye** [comment]
I appreciate lively discussions in github issues - it’s almost like an archaeological record of a project’s design decision. (Though I haven’t always been disciplined about discussing in the most appropriate repo!)

Happy to update MATSS checks with whatever might be generally useful. Same with data preprocessing functions. As for running checks before analysis, it’d be good practice to add that to the template pipeline, and to let deployments of MATSS run additional checks if need be.

**Comment by juniperlsimonis** [comment]
yup, i haven't done anything on timestep stuff with LDATS 0.2.0
