### ISSUE TITLE
Update source for GPDD data

### ISSUE THREAD

**Issue by ha0ye** [weecology/MATSS#142]
See ropensci/rgpdd/issues/6

**Comment by ethanwhite** [comment]
I also added an issue to add this to the retriever (I didn't realize it had actually been publicly released in a meaningful way).

**Comment by ethanwhite** [comment]
https://github.com/weecology/retriever/issues/1359

**Comment by ha0ye** [comment]
re-factor code that imports `gpdd` to switch over to using retriever: `global-population-dynamics`
