### ISSUE TITLE
Plans to integrate Living Planet Index database?

### ISSUE THREAD

**Issue by caseyyoungflesh** [weecology/MATSS#146]
Just curious if there were any plans (or openness) to integrate the [Living Planet Index](http://livingplanetindex.org/) database into MATSS. I believe there would be some redundancy  (e.g., I think LPI also includes GPDD) but seems there should be many unique time series there as well!

**Comment by ha0ye** [comment]
Sort of. We have code to import LPI data over in the [MATSS-forecasting](https://github.com/weecology/MATSS-forecasting) spin-off.

We haven't yet checked for redundancy, but are aware that is an issue to look into.

**Comment by caseyyoungflesh** [comment]
Awesome, thanks for the heads up!
