### ISSUE TITLE
Verify re-sharing and licenses for data

### ISSUE THREAD

**Issue by ha0ye** [weecology/MATSS#155]
How should someone using the data that we make available cite, not just MATSS, but the original datasets?

This could be documented on the dataset summary vignette - https://weecology.github.io/MATSS/articles/dataset-summary.html

Code to output a `.bib` file, based on what datasets are used in a drake plan would be great, too.

**Comment by ha0ye** [comment]
Datasets that we currently distribute as part of `MATSS` should be, instead, downloaded separately, most likely through retriever.

Issues made in https://github.com/weecology/retriever to add these datasets:
- [x] Jornada rodents
- [x] Shortgrass steppe rodents
- [x] Cowley lizards
- [x] Cowley snakes
- [x] Karoo ungulates (part of South African National Parks `/sanparks`)
- [x] Kruger ungulates (part of South African National Parks `/sanparks`)
- [x] Maizuru Bay fish

**Comment by ha0ye** [comment]
Waiting on @gmyenni  to add issues to retriever for Cowley and sanparks data (what are the original sources?)

**Comment by gmyenni** [comment]
Added Cowley. 
Looking into why sanparks is down https://github.com/weecology/retriever/issues/1421
