### ISSUE TITLE
figure out how Drake stores its cache of intermediate results

### ISSUE THREAD

**Issue by ha0ye** [weecology/MATSS#16]
After running, I have a `.drake` folder in my project directory. Ideally, we'll want to set this to be some globally accessible place that can store large files, etc. but is fast enough to pull large objects from, as well, for the reports.

**Comment by ha0ye** [comment]
Looks like Drake uses the [storr](https://github.com/richfitz/storr) package, which has support for quite a few storage backends. See [chapter 13](https://ropenscilabs.github.io/drake-manual/store.html) of the Drake manual.

If we end up using some sort of remote database, note that we'll want to check that it works with whatever parallelization implementation we end up with.

**Comment by ethanwhite** [comment]
Things I've learned in the an hour of exploring this:

1. I can only find discussion of using SQLite, not backends that would support full remote collaboration (PostgreSQL, MySQL, etc.). This doesn't mean it isn't possible to use something else, but it would require more experimentation.
2. Using the SQLite backend we could manage a single SQLite file (potentially large but currently only ~500K) using `piggyback`.
3. There may be issues with parallel with database backends. There is a one year old issue suggesting that it's fruitless (https://github.com/ropensci/drake/issues/181), but the SQLite examples (see below) seem to suggest that it is maybe now possible if undertaken with care.
4. I have successfully run things using the SQLite backend. You can see the code in https://github.com/weecology/MATSS-pipeline/pull/43, which I opened just for communication purposes. Ostensibly this is running parallel in two cores. 

## External SQLite examples

* https://ropenscilabs.github.io/drake-manual/store.html#database-caches
* https://github.com/wlandau/drake-examples/blob/master/dbi/dbi.R

**Comment by ha0ye** [comment]
:thinking: I am running into errors on my own machine, that seem to be related to the issues with parallelization and writing to the SQLite cache file.

I think there is an additional issue, where the `lda_report.md` fails when running in RStudio, but seems to build ok when running from command line. My best guess is that RStudio has some hooks to preview the output of rendering an Rmarkdown file, and this does funny things when running in parallel.
