### ISSUE TITLE
Add class type to MATSS datasets

### ISSUE THREAD

**Issue by ha0ye** [weecology/MATSS#169]
Even if we're not going to do any dispatching on the class, this helps the datasets play well with downstream functions.

**Comment by ha0ye** [comment]
This could potentially also incorporate the flags for whether the dataset is a community / is processed to have equi-timed data... is that even a good idea? @juniperlsimonis

**Comment by juniperlsimonis** [comment]
if nothing else, it could make it easier to ensure that the flag is in a particular element of the class' object. functions like `logLik` often don't do much except point to a particular part of the object to know where to get the values (log like, df, and nobs) to include.
another big benefit of the class type is the method dispatching around simple stuff like print, which allows you to define which elements of the objects are shown at the console and which are there, but not shown (i do this in LDATS with the MCMC output, for example)

**Comment by ha0ye** [comment]
Ooh, yeah, a default `print` method is a good quality-of-life feature!

**Comment by ha0ye** [comment]
me: "Oh dang, a `summary()` function is going to be a pain..."
(5 minutes later)
me: "Oh right, @juniperlsimonis already put one together."
```r
summary.matssdata <- ts_summary
```
