### ISSUE TITLE
Should we set a default license in create_MATSS_compendium?

### ISSUE THREAD

**Issue by ha0ye** [weecology/MATSS#170]
I can see arguments both ways:
* setting a default (e.g. MIT License) makes life easier
* not setting a default is more conservative towards user needs -- if they are going to go through the process of submitting a package to a journal or CRAN, a missing LICENSE field will get picked up on anyway.

We could also split the difference a bit and see about giving a warning/message in a newly created compendium.

**Comment by ethanwhite** [comment]
I like setting a default license with an associate message notifying them that this has been done and how to modify it.
