### ISSUE TITLE
Add data structure check to `run_LDA`

### ISSUE THREAD

**Issue by ha0ye** [weecology/MATSS#50]
Use function `check_data_format()` to see if the data is of the right format, before running the LDA code. Return some kind of default NA object from `run_LDA()` with a warning if not? (an error might stop the whole pipeline?)

**Comment by ha0ye** [comment]
@diazrenata Should I make a PR for your `check-lda-format` branch?

**Comment by diazrenata** [comment]
Not yet, I still need to revisit the passing-of-error-messages!

**Comment by ha0ye** [comment]
closing, with move of LDA functions to weecology/MATSS-LDATS
