### ISSUE TITLE
Initial datasets to include

### ISSUE THREAD

**Issue by ha0ye** [weecology/MATSS#52]
Target these datasets to add to MATSS to test out the initial pipeline and analysis (before a more systematic data collection, see #58)

- [ ] data from [Yenni et al. 2017](https://onlinelibrary.wiley.com/doi/full/10.1111/geb.12566) --  @gmyenni will comment on what to include into MATSS?
- [ ] BioTIME (select from datasets that are suitable for analysis)
- [ ] [POPLER](https://github.com/AldoCompagnoni/popler) (select from datasets that are suitable for analysis)

We also have a previous list compiled in the old MATSS project -  https://github.com/weecology/MATSS/projects/1

**Comment by ha0ye** [comment]
Figure out overlap in datasets that are included in POPLER and BioTIME and Yenni

**Comment by diazrenata** [comment]
For the datasets:
- document format
- and which specific datasets are in there

& build that into MATSS documentation 
& possibly a vignette
