### ISSUE TITLE
BBS data wrangling functions

### ISSUE THREAD

**Issue by ha0ye** [weecology/MATSS#59]
the current dataset that comes out of `get_bbs_data()` (for region 7?) has ~160 time series and ~70k timepoints...

Folks who are familiar with BBS and its usage should probably guide the continued development of this function for generating community time series data.

**Comment by diazrenata** [comment]
Decide how to group BBS data before running it through LDATS

**Comment by gmyenni** [comment]
Here https://github.com/weecology/MATSS/pull/120 I grouped by 'bird conservation region' and summarized by year. Does that work for now?

**Comment by ha0ye** [comment]
closing per #127
