### ISSUE TITLE
trigger drake to re-run when a function has changed

### ISSUE THREAD

**Issue by diazrenata** [weecology/MATSS#63]
drake does not appear to recognize when I change the `run_LDA` function - I need to change something about `pipeline.R` to get it to re-run the LDAs, even when I have messed with `run_LDA` and build + reloaded. This is strange.

**Comment by diazrenata** [comment]
after talking with @ha0ye: looks like this is happening because `drake` isn't necessarily keeping track of updates to the *package code* as opposed to the functions the user defines. (we think.) This relates to distinguishing between MATSS-the-package and MATSS-the-metaanalysis. It might be helpful to split this work into two repositories, so we can be more clear about which functions are 'user-defined' functions and which functions are part of the core MATSS toolkit?

**Comment by ha0ye** [comment]
Just found this and it sounds like it might do the trick?
https://ropensci.github.io/drake/reference/expose_imports.html

**Comment by ha0ye** [comment]
@diazrenata I think I'm going to try using `export_imports` to solve this - I don't think we need anything else, though folks who are going to be running the pipeline can also keep in mind that caches might need to be cleared while LDATS and MATSS development is happening.
