### ISSUE TITLE
Split out LDA analysis from the MATSS package

### ISSUE THREAD

**Issue by ha0ye** [weecology/MATSS#71]
move `run_LDA()` function outside of the package and into MATSS-LDATS repo
move the LDA_report Rmarkdown outside of the package and into MATSS-LDATS repo

**Comment by diazrenata** [comment]
#87, `summary_stats_example` branch.

**Comment by ha0ye** [comment]
I think we still need to remove `run_LDA()` from here, now that it's over in weecology/MATSS-LDATS. (is that right, @diazrenata?)

**Comment by diazrenata** [comment]
That's correct! I believe `matssldats::run_LDA` works (that's how I was calling it to test it), but I didn't want to tinker with `MATSS`.
